apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: azure-cloud-node-manager
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cloud-provider-azure'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: openshift-hack/images/cloud-node-manager-openshift.Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:azure-cloud-node-manager'
