apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: agent-installer-node-agent
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/assisted-installer-agent'
      ref: release-4.13
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.ocp
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:agent-installer-node-agent'
