apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cluster-openshift-controller-manager-operator
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cluster-openshift-controller-manager-operator'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cluster-openshift-controller-manager-operator'
