apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cluster-kube-controller-manager-operator
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cluster-kube-controller-manager-operator'
      ref: release-4.13
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.rhel7
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cluster-kube-controller-manager-operator'
