apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cluster-autoscaler
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/kubernetes-autoscaler'
      ref: release-4.13
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/cluster-autoscaler/Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cluster-autoscaler'
