apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: csi-snapshot-validation-webhook
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/csi-external-snapshotter'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.webhook.openshift.rhel7
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:csi-snapshot-validation-webhook'
