apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cloud-credential-operator
  labels:
    resources-profile: high
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cloud-credential-operator'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cloud-credential-operator'
