apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cluster-node-tuning-operator
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cluster-node-tuning-operator'
      ref: release-4.14
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:base'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-base-openshift-4.12'
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
        - sourcePath: /code/cluster-node-tuning-operator/Dockerfile.centos9
          destinationDir: "."
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.centos9
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cluster-node-tuning-operator'
