apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: docker-builder
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/builder'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.rhel8
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:docker-builder'
