apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: gcp-pd-csi-driver-operator
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/gcp-pd-csi-driver-operator'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.openshift
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:gcp-pd-csi-driver-operator'
