apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kube-storage-version-migrator
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/kubernetes-kube-storage-version-migrator'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/release/Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:kube-storage-version-migrator'
