apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kube-proxy
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/sdn'
      ref: release-4.13
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/kube-proxy/Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:kube-proxy'
