apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: operator-registry
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/operator-framework-olm'
      ref: release-4.13
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
        - sourcePath: /code/operator-registry/Dockerfile.centos9
          destinationDir: "."
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.centos9
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:operator-registry'
