apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: oauth-apiserver
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/oauth-apiserver'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/Dockerfile.rhel7
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:oauth-apiserver'
