apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: operator-marketplace
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/operator-framework/operator-marketplace'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.okd
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:operator-marketplace'
