apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: powervs-machine-controllers
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/machine-api-provider-powervs'
      ref: release-4.13
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:powervs-machine-controllers'
