apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: prometheus-operator-admission-webhook
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/prometheus-operator'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.admission-webhook.ocp
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:prometheus-operator-admission-webhook'
