apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: sdn
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/sdn'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/sdn/Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:base"
      buildArgs:
        - name: ovsver
          value: "2.17"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:sdn'
