apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: thanos
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/thanos'
      ref: release-4.14
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
          - sourcePath: /code/thanos/Dockerfile.ocp
            destinationDir: './'
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.ocp
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:thanos'
