apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: agent-installer-api-server
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/assisted-service'
      ref: release-4.13
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.assisted-service.ocp
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:agent-installer-api-server'
