apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: deployer
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/oc'
      ref: release-4.13
    contextDir: images/deployer
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:cli"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:deployer'
