apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ovn-kubernetes-base
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ovn-kubernetes'
      ref: release-4.14
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.base.rhel9
      from:
        kind: "ImageStreamTag"
        name: "release:base"
      buildArgs:
        - name: ovsver
          value: 3.1.0-33.el9s
        - name: ovnver
          value: 23.03.0-50.el9s
  output:
    to:
      kind: ImageStreamTag
      name: 'release:ovn-kubernetes-base'
