apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: tests
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/origin'
      ref: release-4.14
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
        - sourcePath: /code/tests/Dockerfile.centos9
          destinationDir: "./images/tests"
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/tests/Dockerfile.centos9
      from:
        kind: "ImageStreamTag"
        name: "release:tools"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:tests'
